# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Emit a self-contained debug re-runner at ``<work_dir>/debug/run.py``.

The emitted script provides a uniform debug entry point for every
``build_output/<jit_dir>/`` directory:

- When a sibling ``golden.py`` exists (non-JIT path), inputs are loaded via
  :func:`golden.generate_inputs` and the run is validated against
  :func:`compute_golden` using :func:`pypto.runtime.debug.replay`.
- Otherwise (JIT path), inputs are materialised from shape / dtype
  information embedded in the generated script. The user can edit them
  freely to experiment.

So the user only needs to remember one command::

    python build_output/<jit_dir>/debug/run.py
"""

from pathlib import Path

import torch

from pypto.ir.compiled_program import ParamInfo, _to_torch_dtype
from pypto.pypto_core.ir import ParamDirection

_TORCH_DTYPE_NAMES: dict[torch.dtype, str] = {
    torch.float16: "torch.float16",
    torch.float32: "torch.float32",
    torch.float64: "torch.float64",
    torch.bfloat16: "torch.bfloat16",
    torch.int8: "torch.int8",
    torch.int16: "torch.int16",
    torch.int32: "torch.int32",
    torch.int64: "torch.int64",
    torch.uint8: "torch.uint8",
    torch.bool: "torch.bool",
}
for _name in ("uint16", "uint32", "uint64"):
    _dt = getattr(torch, _name, None)
    if _dt is not None:
        _TORCH_DTYPE_NAMES[_dt] = f"torch.{_name}"
del _name, _dt


def write_run_script(
    work_dir: Path | str,
    param_infos: list[ParamInfo],
    *,
    platform: str | None = None,
) -> Path:
    """Emit ``<work_dir>/debug/run.py``.

    Args:
        work_dir: A ``build_output/<jit_dir>/`` produced by ``ir.compile()``.
        param_infos: Orchestration parameter metadata, in call order.
            Obtain via :func:`pypto.ir.compiled_program.extract_param_infos`.
        platform: Default platform baked into the generated CLI's
            ``--platform`` argument. ``None`` falls back to ``"a2a3sim"``.

    Returns:
        The path to the written ``debug/run.py``.
    """
    work_dir = Path(work_dir)
    debug_dir = work_dir / "debug"
    debug_dir.mkdir(parents=True, exist_ok=True)
    out_path = debug_dir / "run.py"
    out_path.write_text(_render(param_infos, platform), encoding="utf-8")
    return out_path


def _render(param_infos: list[ParamInfo], platform: str | None) -> str:
    init_lines = [_init_expr_for(p) for p in param_infos]
    names = ", ".join(p.name for p in param_infos)
    default_platform = platform or "a2a3"
    indented_inits = "\n".join("    " + line for line in init_lines) or "    pass"

    return f'''"""Auto-generated debug runner — do not edit by hand.

Re-execute the kernel in the parent build_output directory:

    python {{this_file}}

When a sibling ``golden.py`` exists, inputs are loaded via
``golden.generate_inputs`` and the run is validated against
``compute_golden``. Otherwise the inputs declared inline in
``_inline_inputs`` are used (edit them freely to experiment).

Generated by pypto.runtime.debug.run_script_writer.
"""

import argparse
import importlib.util
import sys
from pathlib import Path

import torch

_WORK_DIR = Path(__file__).resolve().parent.parent


def _load_golden_inputs():
    """Return the input tensors declared by ``golden.py``, or None."""
    golden_py = _WORK_DIR / "golden.py"
    if not golden_py.exists():
        return None
    spec = importlib.util.spec_from_file_location("_run_golden", golden_py)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return [value for _, value in module.generate_inputs({{"name": "Default"}})]


def _inline_inputs():
    """Materialise inputs from shape / dtype info embedded at compile time."""
{indented_inits}
    return [{names}]


def main(argv=None) -> int:
    from pypto.runtime import RunConfig  # noqa: PLC0415
    from pypto.runtime.debug import replay  # noqa: PLC0415

    parser = argparse.ArgumentParser(
        description="Re-execute this build_output directory with DFX flags.",
    )
    parser.add_argument("--platform", default="{default_platform}")
    parser.add_argument("--device-id", type=int, default=0)
    parser.add_argument("--pmu", type=int, default=0, metavar="LEVEL")
    parser.add_argument("--swimlane", action="store_true")
    parser.add_argument("--dump-tensor", action="store_true")
    parser.add_argument("--dep-gen", action="store_true")
    parser.add_argument(
        "--no-recompile",
        action="store_true",
        help="Reuse cached binaries (faster, but ignores cpp edits)",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip golden validation even when golden.py is present.",
    )
    parser.add_argument(
        "--log-level",
        default=None,
        metavar="LEVEL",
        help=(
            "PyPTO runtime log level (debug, v0..v9, info, warn, error, null). "
            "Equivalent to setting PYPTO_RUNTIME_LOG=<level> in the environment."
        ),
    )
    parser.add_argument(
        "--log-sync-pypto",
        action="store_true",
        help="When used with --log-level, mirror the level onto PyPTO's C++ logger.",
    )
    args = parser.parse_args(argv)

    if args.log_level is not None:
        from pypto.runtime.log_config import configure_log  # noqa: PLC0415
        configure_log(args.log_level, sync_pypto=args.log_sync_pypto)

    golden_inputs = None if args.no_validate else _load_golden_inputs()
    if golden_inputs is not None:
        tensors = golden_inputs
        validate = True
    else:
        tensors = _inline_inputs()
        validate = False

    config = RunConfig(
        platform=args.platform,
        device_id=args.device_id,
        enable_pmu=args.pmu,
        enable_l2_swimlane=args.swimlane,
        enable_dump_tensor=args.dump_tensor,
        enable_dep_gen=args.dep_gen,
    )
    replay(
        _WORK_DIR,
        *tensors,
        config=config,
        recompile=not args.no_recompile,
        validate=validate,
    )
    print(f"Replay finished. DFX artefacts (if any) under {{_WORK_DIR / 'dfx_outputs'}}")
    if validate:
        print("Golden validation: PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _init_expr_for(p: ParamInfo) -> str:
    """Return a Python statement initialising parameter *p*.

    Scalars (no shape) are not auto-materialised in v1 — emit a placeholder
    line so the user can hand-edit. Dynamic dimensions (``-1``) are filled
    with ``1`` so the generated file is at least syntactically valid.
    """
    if p.shape is None:
        return f"{p.name} = None  # TODO: scalar param — set a ctypes value"

    torch_dtype = _to_torch_dtype(p.dtype)
    dtype_str = _TORCH_DTYPE_NAMES.get(torch_dtype, "torch.float32") if torch_dtype else "torch.float32"
    concrete_shape = tuple(d if d >= 0 else 1 for d in p.shape)
    has_dynamic = any(d < 0 for d in p.shape)
    comment = "  # NOTE: dynamic dim(s) filled with 1 — edit as needed" if has_dynamic else ""

    if p.direction == ParamDirection.Out:
        return f"{p.name} = torch.zeros({concrete_shape!r}, dtype={dtype_str}){comment}"
    return f"{p.name} = torch.randn({concrete_shape!r}, dtype={dtype_str}){comment}"
