# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Compiled program wrapper returned by :func:`ir.compile`.

Provides a Triton-like callable API: compile once, then call with
torch tensors::

    compiled = ir.compile(MyProgram)
    compiled(a, b, c)                    # in-place on default sim, device 0
    c = compiled(a, b)                   # return style
    compiled(a, b, c, device=1)          # specify device at call time
"""

import ctypes
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch

from pypto.backend import BackendType
from pypto.pypto_core import DataType
from pypto.pypto_core import backend as _backend_core
from pypto.pypto_core.ir import (
    ConstInt,
    FunctionType,
    ParamDirection,
    Program,
    ScalarType,
    ShapedType,
)
from pypto.runtime.device_tensor import DeviceTensor

# Type alias for arguments accepted by CompiledProgram.__call__().
# Tensor params accept ``torch.Tensor`` (host) or :class:`DeviceTensor`
# (worker-resident — skips H2D/D2H, see ``pypto.runtime.DeviceTensor``).
# Scalar params accept Python primitives or ctypes scalars (which are
# coerced to the correct ctypes type internally).
CallArg = torch.Tensor | DeviceTensor | int | float | bool | ctypes._SimpleCData

# IR DataType -> torch.dtype mapping.
# Keyed by string because nanobind DataType instances are not singletons,
# so dict lookup by object identity / hash may fail even for equal values.
_DATATYPE_TO_TORCH: dict[str, torch.dtype] = {
    "fp16": torch.float16,
    "fp32": torch.float32,
    "fp64": torch.float64,
    "bfloat16": torch.bfloat16,
    "int8": torch.int8,
    "int16": torch.int16,
    "int32": torch.int32,
    "int64": torch.int64,
    "uint8": torch.uint8,
    "bool": torch.bool,
    "index": torch.int64,
}
# uint16/32/64 were added in PyTorch 2.3; register only if available
for _name in ("uint16", "uint32", "uint64"):
    _torch_dtype = getattr(torch, _name, None)
    if _torch_dtype is not None:
        _DATATYPE_TO_TORCH[_name] = _torch_dtype
del _name, _torch_dtype

# IR DataType -> ctypes scalar constructor mapping.
# Used to wrap Python int/float/bool values into the correct ctypes scalar
# when calling a compiled program with scalar parameters.
_DATATYPE_TO_CTYPE: dict[str, type[ctypes._SimpleCData]] = {
    "fp16": ctypes.c_float,  # no native half; promote to float
    "fp32": ctypes.c_float,
    "fp64": ctypes.c_double,
    "bfloat16": ctypes.c_float,  # no native bfloat16; promote to float
    "int8": ctypes.c_int8,
    "int16": ctypes.c_int16,
    "int32": ctypes.c_int32,
    "int64": ctypes.c_int64,
    "uint8": ctypes.c_uint8,
    "uint16": ctypes.c_uint16,
    "uint32": ctypes.c_uint32,
    "uint64": ctypes.c_uint64,
    "bool": ctypes.c_bool,
    "index": ctypes.c_int64,
}


def _to_torch_dtype(dtype: DataType) -> torch.dtype | None:
    """Convert an IR DataType to the corresponding torch.dtype."""
    return _DATATYPE_TO_TORCH.get(str(dtype))


@dataclass
class _ParamInfo:
    """Metadata for a single orchestration function parameter."""

    name: str
    direction: ParamDirection
    shape: list[int] | None  # None for scalar params
    dtype: DataType


def _extract_param_infos(program: Program) -> tuple[list[_ParamInfo], list[int], list[Any]]:
    """Extract parameter metadata from the program's orchestration function.

    Args:
        program: A compiled IR Program.

    Returns:
        Tuple of (param_infos, output_indices, return_types).

    Raises:
        ValueError: If no Orchestration function is found.
    """
    # Prefer the Orchestration function; fall back to the sole function when
    # orchestration is auto-generated by codegen (single-kernel programs).
    orch_func = next(
        (f for f in program.functions.values() if f.func_type == FunctionType.Orchestration),
        None,
    )
    if orch_func is None:
        funcs = list(program.functions.values())
        if len(funcs) == 1:
            orch_func = funcs[0]
        else:
            raise ValueError(
                "Program has no Orchestration function and multiple InCore functions. "
                "Add an explicit Orchestration function to define the call signature."
            )

    param_infos: list[_ParamInfo] = []
    output_indices: list[int] = []

    for i, (param, direction) in enumerate(zip(orch_func.params, orch_func.param_directions, strict=True)):
        param_type = param.type
        shape: list[int] | None = None

        if isinstance(param_type, ShapedType):
            dtype = param_type.dtype
            shape = [dim.value if isinstance(dim, ConstInt) else -1 for dim in param_type.shape]
        elif isinstance(param_type, ScalarType):
            dtype = param_type.dtype
        else:
            raise TypeError(
                f"Unsupported parameter type for {param.name_hint!r}: {type(param_type).__name__}. "
                f"Expected ShapedType or ScalarType."
            )

        param_infos.append(_ParamInfo(name=param.name_hint, direction=direction, shape=shape, dtype=dtype))

        # Only pure Out params can be auto-allocated in return-style calls.
        # InOut params require an initial value from the caller, so they must
        # be passed explicitly like inputs.
        if direction == ParamDirection.Out:
            output_indices.append(i)

    return param_infos, output_indices, list(orch_func.return_types)


def _default_platform(backend_type: BackendType) -> str:
    """Return the default simulator platform for a backend type.

    The mapping from backend to platform name lives on the per-backend
    BackendHandler so adding a new backend only requires implementing the
    handler.
    """
    return _backend_core.get_backend_instance(backend_type).get_handler().get_default_sim_platform()


class CompiledProgram:
    """A compiled PyPTO program that can be called with torch tensors.

    Returned by :func:`ir.compile`.  ``CompiledProgram`` is a **compiled
    artifact** -- it stores the compilation output, target platform, and IR
    metadata.  The ``device`` index is provided at call time.

    Two calling conventions:

    **In-place** (output passed as argument)::

        compiled = ir.compile(MyProgram)
        compiled(a, b, c)  # c modified in-place on device

    **Return** (program has a return value)::

        compiled = ir.compile(MyProgram)
        c = compiled(a, b)  # output allocated and returned

    Device selection is a keyword argument on each call::

        compiled(a, b, c, device=1)

    For backward compatibility, ``CompiledProgram`` also behaves like a
    path string via ``__str__`` and ``__fspath__``, so existing code that
    does ``os.path.join(ir.compile(prog), "kernels")`` continues to work.
    """

    __test__ = False  # Not a pytest test class

    def __init__(
        self,
        program: Program,
        output_dir: str,
        *,
        backend_type: BackendType = BackendType.Ascend910B,
        platform: str | None = None,
    ) -> None:
        self._program = program
        self._output_dir = Path(output_dir).resolve()
        self._backend_type = backend_type
        self._platform = platform or _default_platform(backend_type)
        # Lazy metadata -- extracted on first call
        self._param_infos: list[_ParamInfo] | None = None
        self._output_indices: list[int] | None = None
        self._return_types: list[Any] | None = None

        self._emit_debug_runner()

    def _emit_debug_runner(self) -> None:
        """Write ``<output_dir>/debug/run.py`` so the kernel can be replayed via
        ``python .../debug/run.py``.

        Best-effort: programs that lack a clean orchestration entry (unusual
        shapes, edge-case codegen) cannot have their param signature extracted
        here. In that case the file is skipped — the replay CLI is still usable
        directly against the output directory.

        Disable globally by setting ``PYPTO_EMIT_DEBUG_RUNNER=0`` (also accepts
        ``false`` / ``no``).
        """
        if os.environ.get("PYPTO_EMIT_DEBUG_RUNNER", "").strip().lower() in ("0", "false", "no"):
            return

        from pypto.runtime.debug.run_script_writer import write_run_script  # noqa: PLC0415

        try:
            param_infos, _, _ = self._get_metadata()
        except (ValueError, TypeError):
            return
        write_run_script(self._output_dir, param_infos, platform=self._platform)

    # --- Properties -----------------------------------------------------------

    @property
    def output_dir(self) -> Path:
        """Path to compiled artifacts (kernels/, orchestration/, etc.)."""
        return self._output_dir

    @property
    def program(self) -> Program:
        """The original IR Program (pre-optimization passes)."""
        return self._program

    @property
    def backend_type(self) -> BackendType:
        """Backend type used during compilation."""
        return self._backend_type

    @property
    def platform(self) -> str:
        """Target execution platform (e.g. ``"a2a3sim"``, ``"a5"``)."""
        return self._platform

    # --- Backward compatibility: behave like a path string --------------------

    def __str__(self) -> str:
        return str(self._output_dir)

    def __repr__(self) -> str:
        return f"CompiledProgram({self._output_dir!s})"

    def __fspath__(self) -> str:
        """Allow ``os.path.join(compiled, ...)`` and ``Path(compiled)``."""
        return str(self._output_dir)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, CompiledProgram):
            return self._output_dir == other._output_dir
        if isinstance(other, (str, os.PathLike)):
            return str(self._output_dir) == str(other)
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._output_dir)

    # --- Metadata (lazy) ------------------------------------------------------

    def _get_metadata(self) -> tuple[list[_ParamInfo], list[int], list[Any]]:
        """Return (param_infos, output_indices, return_types), extracting on first call."""
        if self._param_infos is None:
            self._param_infos, self._output_indices, self._return_types = _extract_param_infos(self._program)
        return self._param_infos, self._output_indices, self._return_types  # type: ignore[return-value]

    @property
    def param_names(self) -> list[str]:
        """Parameter names of the orchestration function."""
        param_infos, _, _ = self._get_metadata()
        return [p.name for p in param_infos]

    @property
    def output_indices(self) -> list[int]:
        """Indices of pure Out parameters (eligible for auto-allocation)."""
        _, out_idx, _ = self._get_metadata()
        return list(out_idx)

    @property
    def has_return(self) -> bool:
        """Whether the orchestration function has return values."""
        _, _, return_types = self._get_metadata()
        return len(return_types) > 0

    # --- Callable API ---------------------------------------------------------

    def __call__(  # noqa: PLR0912 — dispatch logic with several arg-shape branches
        self,
        *args: CallArg,
        config: Any = None,
    ) -> torch.Tensor | tuple[torch.Tensor, ...] | None:
        """Execute the compiled program with torch tensors and/or scalars.

        Args match the orchestration function's parameter order.  For
        **in-place** style, pass all tensors (including outputs) and the
        output tensors are modified on device.  For **return** style,
        pass only input tensors and the outputs are allocated and returned.

        Scalar parameters (``pl.Scalar[...]``) accept Python ``int``,
        ``float``, ``bool``, or ``ctypes`` scalar values.

        Args:
            *args: Positional arguments — ``torch.Tensor`` for tensor
                params, ``int | float | bool | ctypes._SimpleCData`` for
                scalar params.
            config: Optional :class:`~pypto.runtime.runner.RunConfig` for
                device index, profiling, etc.  Defaults to ``RunConfig()``.

        Returns:
            ``None`` for in-place calls, a single ``torch.Tensor`` or a
            ``tuple`` for return-style calls.

        Raises:
            TypeError: If argument count or types do not match.
        """
        param_infos, output_indices, return_types = self._get_metadata()
        n_params = len(param_infos)
        n_inputs = n_params - len(output_indices)
        has_return = len(return_types) > 0
        return_style = has_return and len(args) == n_inputs

        # Determine calling convention
        if len(args) == n_params:
            all_args: list[CallArg] = list(args)
        elif return_style:
            all_args = self._build_full_args(args, param_infos, output_indices)
        else:
            expected = f"{n_params} (in-place)"
            if has_return:
                expected += f" or {n_inputs} (return)"
            raise TypeError(
                f"CompiledProgram expects {expected} arguments, got {len(args)}. "
                f"Parameters: {[p.name for p in param_infos]}"
            )

        # Coerce args: wrap Python scalars into ctypes, validate tensor vs scalar
        coerced: list[torch.Tensor | DeviceTensor | ctypes._SimpleCData] = []
        for info, arg in zip(param_infos, all_args, strict=True):
            if info.shape is None:
                # Scalar parameter
                if isinstance(arg, torch.Tensor):
                    raise TypeError(f"Parameter {info.name!r} is a scalar ({info.dtype}); got torch.Tensor")
                if isinstance(arg, ctypes._SimpleCData):
                    expected_ctype = _DATATYPE_TO_CTYPE.get(str(info.dtype))
                    if expected_ctype is not None and not isinstance(arg, expected_ctype):
                        raise TypeError(
                            f"Parameter {info.name!r} expects {expected_ctype.__name__} "
                            f"for dtype {info.dtype}; got {type(arg).__name__}"
                        )
                    coerced.append(arg)
                else:
                    ctype = _DATATYPE_TO_CTYPE.get(str(info.dtype))
                    if ctype is None:
                        raise TypeError(f"Unsupported scalar dtype {info.dtype} for parameter {info.name!r}")
                    coerced.append(ctype(arg))
            else:
                # Tensor parameter — accept torch.Tensor (host) or DeviceTensor (worker-resident)
                if not isinstance(arg, (torch.Tensor, DeviceTensor)):
                    raise TypeError(
                        f"Parameter {info.name!r} is a tensor; got {type(arg).__name__}. "
                        f"Pass a torch.Tensor (host) or DeviceTensor (worker-resident)."
                    )
                # Early shape/dtype validation for DeviceTensor.  ``torch.Tensor`` already
                # carries its shape/dtype natively and downstream codegen has its own
                # checks; ``DeviceTensor`` is opaque, so a mismatch would only surface
                # deep inside the runtime with a far less actionable error.  Skip the
                # check on dynamic dims (any ``-1`` in info.shape) since the IR has not
                # committed to a concrete shape there.
                if isinstance(arg, DeviceTensor):
                    self._validate_device_tensor(arg, info)
                coerced.append(arg)

        from pypto.runtime.runner import RunConfig, _DfxOpts, execute_compiled  # noqa: PLC0415

        if config is None:
            config = RunConfig()

        execute_compiled(
            self._output_dir,
            coerced,
            platform=self._platform,
            device_id=config.device_id,
            pto_isa_commit=config.pto_isa_commit,
            dfx=_DfxOpts.from_run_config(config),
            block_dim=config.block_dim,
            aicpu_thread_num=config.aicpu_thread_num,
        )

        if not return_style:
            return None
        # Output indices always correspond to tensor params (scalars cannot be Out
        # direction), so the elements are guaranteed to be torch.Tensor.
        outputs = [coerced[i] for i in output_indices]
        assert all(isinstance(o, torch.Tensor) for o in outputs)
        return outputs[0] if len(outputs) == 1 else tuple(outputs)  # type: ignore[return-value]

    @staticmethod
    def _validate_device_tensor(arg: DeviceTensor, info: _ParamInfo) -> None:
        """Check a ``DeviceTensor`` arg against IR parameter metadata.

        Raises:
            TypeError: when shape or dtype disagrees with ``info``.

        Static IR shapes are compared exactly; dynamic dims (any ``-1`` in
        ``info.shape``) are skipped.  Dtypes that the runtime can't map to
        torch are also skipped.
        """
        if info.shape is not None and all(d >= 0 for d in info.shape):
            expected_shape = tuple(info.shape)
            if expected_shape != arg.shape:
                raise TypeError(
                    f"Parameter {info.name!r} expects shape {expected_shape}; "
                    f"got DeviceTensor shape {arg.shape}"
                )
        expected_dtype = _to_torch_dtype(info.dtype)
        if expected_dtype is not None and arg.dtype != expected_dtype:
            raise TypeError(
                f"Parameter {info.name!r} expects dtype {expected_dtype}; got DeviceTensor dtype {arg.dtype}"
            )

    @staticmethod
    def _build_full_args(
        input_args: tuple[CallArg, ...],
        param_infos: list[_ParamInfo],
        output_indices: list[int],
    ) -> list[CallArg]:
        """Allocate output tensors and interleave with input args."""
        output_set = set(output_indices)
        all_tensors: list[CallArg] = []
        input_idx = 0

        for i, info in enumerate(param_infos):
            if i in output_set:
                if info.shape is None:
                    raise ValueError(f"Cannot allocate output tensor {info.name!r}: no shape in IR")
                if any(d < 0 for d in info.shape):
                    raise ValueError(
                        f"Cannot allocate output tensor {info.name!r}: shape {info.shape} "
                        f"contains dynamic dimensions. Pass all tensors explicitly (in-place style)."
                    )
                torch_dtype = _to_torch_dtype(info.dtype)
                if torch_dtype is None:
                    raise ValueError(f"Unsupported dtype {info.dtype} for output tensor {info.name!r}")
                all_tensors.append(torch.zeros(info.shape, dtype=torch_dtype))
            else:
                all_tensors.append(input_args[input_idx])
                input_idx += 1

        return all_tensors


# Public re-exports for callers (e.g. ir.compile()) that need orchestration
# parameter metadata without instantiating a full CompiledProgram.
ParamInfo = _ParamInfo
extract_param_infos = _extract_param_infos
