# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""End-to-end on-board test for the dispatch predicate authored through the
pypto DSL (``pl.spmd_submit(..., predicate=(gate[0, 0] > 0))``).

This is the frontend counterpart of the runtime's own hand-written
``predicated_dispatch`` scene test: instead of building an ``L0TaskPredicate``
in orchestration C++ by hand, the orchestration is generated by pypto codegen
from the DSL predicate. It proves the whole chain — DSL -> IR -> pass pipeline
-> orchestration codegen -> runtime scheduler — behaves as designed.

Task chain (all single-block SPMD tasks in one ``manual_scope``)::

    x_producer   writes X := SENTINEL (42.0)
    clobber      writes X := POISON  (999.0), but carries
                 predicate = (gate[0, 0] > 0) and depends on x_producer.
                 The scheduler reads gate[0, 0] at the dispatch point and
                 dispatches the clobber only when gate[0, 0] > 0.
    consumer     copies X -> OUT, depending on the clobber's TaskId.

``gate`` is a host-initialised INT32 input, so its value is current from the
start (no producer, no dep needed for the predicate operand).

Cases:

* ``gate = 0`` -> predicate FALSE -> clobber NOT dispatched -> X stays 42.0 ->
  OUT = 42.0. Proves non-dispatch AND that the inline-retired clobber still
  settles its fanout so the consumer (deps=[clobber_tid]) unlocks.
* ``gate = 1`` -> predicate TRUE -> clobber dispatched -> X = 999.0 ->
  OUT = 999.0. Proves the dispatch path is taken when the predicate holds.
"""

from typing import Any

import pypto.language as pl
import pytest
from harness.core.harness import PLATFORMS, DataType, PTOTestCase, TensorSpec
from pypto.ir.pass_manager import OptimizationStrategy

_R = 128
_C = 128
_SENTINEL = 42.0
_POISON = 999.0


def _build_program():
    R, C = _R, _C
    SENTINEL, POISON = _SENTINEL, _POISON

    @pl.program
    class PredicatedDispatchProgram:
        @pl.function(type=pl.FunctionType.InCore)
        def x_producer(self, x: pl.Out[pl.Tensor[[R, C], pl.FP32]]) -> pl.Tensor[[R, C], pl.FP32]:
            t: pl.Tile[[R, C], pl.FP32] = pl.tile.full([R, C], dtype=pl.FP32, value=SENTINEL)
            return pl.store(t, [0, 0], x)

        @pl.function(type=pl.FunctionType.InCore)
        def clobber(self, x: pl.Out[pl.Tensor[[R, C], pl.FP32]]) -> pl.Tensor[[R, C], pl.FP32]:
            # Overwrites X wholesale with POISON. Runs only when the predicate holds.
            t: pl.Tile[[R, C], pl.FP32] = pl.tile.full([R, C], dtype=pl.FP32, value=POISON)
            return pl.store(t, [0, 0], x)

        @pl.function(type=pl.FunctionType.InCore)
        def consumer(
            self, x: pl.Tensor[[R, C], pl.FP32], out: pl.Out[pl.Tensor[[R, C], pl.FP32]]
        ) -> pl.Tensor[[R, C], pl.FP32]:
            t: pl.Tile[[R, C], pl.FP32] = pl.load(x, [0, 0], [R, C])
            return pl.store(t, [0, 0], out)

        @pl.function(type=pl.FunctionType.Orchestration)
        def main(
            self,
            x: pl.Out[pl.Tensor[[R, C], pl.FP32]],
            gate: pl.Tensor[[R, C], pl.INT32],
            out: pl.Out[pl.Tensor[[R, C], pl.FP32]],
        ) -> pl.Tensor[[R, C], pl.FP32]:
            with pl.manual_scope():
                x, xp_tid = pl.spmd_submit(self.x_producer, x, core_num=1)
                # Predicated clobber: reads gate[0, 0] at the dispatch point.
                x, clobber_tid = pl.spmd_submit(
                    self.clobber,
                    x,
                    core_num=1,
                    deps=[xp_tid],
                    predicate=(gate[0, 0] > 0),
                )
                # Consumer depends on the clobber TaskId even when the clobber is
                # predicate-skipped — the retired task still settles fanout.
                out, _ = pl.spmd_submit(self.consumer, x, out, core_num=1, deps=[clobber_tid])
            return out

    return PredicatedDispatchProgram


class _PredicatedDispatchPTO(PTOTestCase):
    """Drives the DSL-authored predicated dispatch for one gate value."""

    __test__ = False

    def __init__(self, *, gate_value: int, platform: str | None = None, config=None):
        super().__init__(config, platform=platform)
        self._gate_value = gate_value

    def get_name(self) -> str:
        return f"predicated_dispatch_gate{self._gate_value}_{_R}x{_C}"

    def get_strategy(self) -> OptimizationStrategy:
        return OptimizationStrategy.Default

    def get_program(self) -> Any:
        return _build_program()

    def define_tensors(self) -> list[TensorSpec]:
        return [
            TensorSpec("x", [_R, _C], DataType.FP32, init_value=-1.0),
            TensorSpec("gate", [_R, _C], DataType.INT32, init_value=self._gate_value),
            TensorSpec("out", [_R, _C], DataType.FP32, init_value=-1.0, is_output=True),
        ]

    def compute_expected(self, tensors, params=None):
        # gate > 0 -> clobber dispatched -> POISON; else the SENTINEL survives.
        final = _POISON if self._gate_value > 0 else _SENTINEL
        tensors["out"][:] = final


class TestPredicatedDispatch:
    """The DSL predicate must skip / dispatch the clobber per gate value."""

    @pytest.mark.parametrize("platform", PLATFORMS)
    @pytest.mark.parametrize("gate_value", [0, 1], ids=["predicate_false_skips", "predicate_true_dispatches"])
    def test_predicated_dispatch(self, test_runner, platform, gate_value):
        result = test_runner.run(_PredicatedDispatchPTO(gate_value=gate_value, platform=platform))
        assert result.passed, f"predicated dispatch (gate={gate_value}) failed: {result.error}"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
