name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve PyPTO's documentation!

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Which document or section needs improvement?
      placeholder: e.g., "docs/dev/00-ir_overview.md, section on Type System"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong or Missing?
      description: Describe the issue with the current documentation
      placeholder: |
        e.g.,
        - Incorrect example code that doesn't work
        - Missing explanation of a key concept
        - Unclear wording that's confusing
        - Outdated information that no longer matches the code
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Describe what should be added, changed, or clarified
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help
    validations:
      required: false
