name: IR Pass / Transform Bug
description: Report a bug in an IR pass or transformation
title: "[Pass Bug] "
labels: ["bug", "ir-pass"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a pass bug! Please provide the **Before** and **Expected** IR using the `@pl.program` pattern.

  - type: input
    id: pass_name
    attributes:
      label: Pass Name
      description: Which pass exhibits the bug? Please enter the exact pass or transformation name.
      placeholder: e.g., InitMemRef, BasicMemoryReuse, InsertSync, AddAlloc
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the bug
      placeholder: e.g., "Constant folding incorrectly transforms tensor operations"
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Git Commit ID
      description: "Exact commit hash where the issue occurs. Run `git rev-parse HEAD` to get the current commit ID."
      placeholder: e.g., f04cde8a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d
    validations:
      required: true

  - type: textarea
    id: before_ir
    attributes:
      label: Before IR (Input)
      description: "**Required:** IR before the pass, using `@pl.program` syntax"
      placeholder: |
        ```python
        import pypto.language as pl

        @pl.program
        class Before:
            @pl.function
            def main(self, x: pl.Tensor[[64], pl.FP32]) -> pl.Tensor[[64], pl.FP32]:
                y = pl.add(x, x)
                return y
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: expected_ir
    attributes:
      label: Expected IR (After Transformation)
      description: "**Required:** Expected IR after the pass"
      placeholder: |
        ```python
        @pl.program
        class Expected:
            @pl.function
            def main(self, x: pl.Tensor[[64], pl.FP32]) -> pl.Tensor[[64], pl.FP32]:
                y = pl.mul(x, 2.0)  # Expected optimization
                return y
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: actual_ir
    attributes:
      label: Actual IR or Error
      description: What actually happens? (Transformed IR or error message)
      placeholder: |
        Paste the actual output IR or error message here
      render: shell
    validations:
      required: true

  - type: dropdown
    id: npu_kind
    attributes:
      label: NPU Kind (if relevant)
      description: Target NPU architecture
      options:
        - N/A (not hardware-specific)
        - Ascend 910B
        - Ascend 910C
        - Other (please specify in description)
    validations:
      required: false

  - type: dropdown
    id: host_arch
    attributes:
      label: Host Architecture (if relevant)
      description: CPU architecture of the host machine
      options:
        - N/A
        - x86_64
        - aarch64
        - Other (please specify)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help
    validations:
      required: false
